### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by marczellm** [lanza/lldb-vscode#11]
It would be great if this worked on Linux. What would have to be done?

**Comment by lanza** [comment]
Not impossible. I just haven't. It requires a couple local changes on top of lldb to account for some of the features I have added in. I'll check into it. Though some of the other plugins are going to have much more feature support, so unless you really care about the free launch tool I'd suggest checking those out.

**Comment by default-writer** [comment]
Visual Studio Code, on darwin images it should execute:

`/root/.vscode-server/extensions/lanza.lldb-vscode-0.2.3/bin/darwin/bin/lldb-vscode`

in fact, it executes on path 

`/root/.vscode-server/extensions/lanza.lldb-vscode-0.2.3/bin/linux/bin/lldb-vscode`

which is incorrect in .dockercontainer using Ubuntu 20.04

The main difference is the one path 'linux' changed to 'darwin'. That whould be awesome if it chooses the correct path on launch
