### ISSUE TITLE
application keeps running after debug stops

### ISSUE THREAD

**Issue by dvirtz** [lanza/lldb-vscode#3]
running the following program:
```C++
#include <iostream>

int main() {
  std::cout << "Hello World!\n"; 
  while(true);
}
```
with the following debug conf:
```json
    {
      "type": "lldb-vscode",
      "request": "launch",
      "name": "Debug",
      "program": "${command:cmake.launchTargetPath}",
      "args": [],
      "env": [],
      "cwd": "${workspaceRoot}"
    }
```
I stop debugging while the infinite loops runs but the application keeps running.

**Comment by lanza** [comment]
Fixed in https://github.com/lanza/lldb-vscode/commit/0d15ede9ee0612dd926be92b40685d4841d52987 and version 0.2.1 on the VSCode store.
