### ISSUE TITLE
Couldn't find a debug adapter descriptor for debug type 'lldb-vscode'

### ISSUE THREAD

**Issue by cdwilson** [lanza/lldb-vscode#6]
I'm getting the following error when I try to launch a debug session:

![image](https://user-images.githubusercontent.com/14631/86521387-08cd2f00-be05-11ea-9e15-fa6844417646.png)

The extension appears to have been installed correctly:

![image](https://user-images.githubusercontent.com/14631/86521416-63668b00-be05-11ea-86f5-33038125c248.png)

Here's my `launch.json` configuration:

```
   {
      "type": "lldb-vscode",
      "request": "launch",
      "name": "lldb-vscode Debug",
      "program": "${fileDirname}/${fileBasenameNoExtension}",
      "args": [],
      "env": [],
      "cwd": "${workspaceRoot}"
    }
```

Any idea what might be causing this or how to debug further?

**Comment by bojomojo** [comment]
same problem here. Was there any progress on this?

**Comment by lanza** [comment]
Can't say I can tell what's going on from this limited of info. At any rate, I no longer work on lldb and I certainly expect the codelldb plugin to be a better option for most purposes going forward.

**Comment by lanza** [comment]
I'm guessing this was a problem with some API update between VSCode versions. I ran into this problem as well. But I pushed a new build and things work just fine now.
